''' This file is automatically generated
Any changes may be overwritten'''

lbl_dict = {'g_JL':'5.11',
    'g_J_1':'6.3',
    'g_J_2':'6.4',
    'g_Q_1':'6.6',
    'g_Q_1_y1_4':'6.7',
    'g_Q_2':'6.11',
    'g_LJQ_1':'6.12',
    'g_LJQ_2':'6.16',
    'g_QJQ':'6.24',
    'g_QJ_1':'6.25',
    'g_QJ_2':'6.26',
    'g_P_2':'7.3',
    'g_P_3':'7.4',
    'h_LJQ_1':'3.3',
    'h_LJQ_2':'3.7',
    'h_LJ_1':'3.8',
    'h_QJQ_1':'3.11',
    'h_QJQ_2':'3.12',
    'h_QJ_1':'3.13',
    'h_QJ_2':'3.14',
    'h_P_1':'4.2',
    'h_P_2':'4.3'
}
